const HERO_QUOTES = [
  "Master Your Technical Interviews",
  "techpad.app Is The Best",
  "Enjoy The Interview Playground",
  "Just Hope That Resume Got Through",
  "Did You Techpad Today?",
  "Start The New Year Right!",
  "You Want That Job?",
  "Practice Your Technical Skills",
  "Ace Your Next Interview",
  "Get Interview Ready",
  "Level Up Your Career",
  "Land Your Dream Role",
  "Prep Like a Pro",
  "Show Them What You Got",
  "Crush Technical Rounds",
  "Build Interview Confidence",
  "Ready to Impress?",
  "Sharpen Your Skills",
  "Stand Out From The Crowd",
  "Own The Interview Room",
  "Make Your Move",
  "Time to Level Up",
  "Prove Your Worth",
  "Show Your Expertise",
  "Become Interview Ready",
  "You're Not Cooked.",
  "Your future depends on this.",
  "Get A Fucking Grip.",
  "Fix Your Life",
  "Can You Even Code",
  "AI Will Take Over",
  "The Future is Now",
  "The World is Yours",
  "AI Has Nothing On You",
  "Get Ready",
  "Feel The Pressure",
  "Final Round? What's That?",
  "Shut Up And Do It",
  "Stop Coping, Focus!",
  "This Is Where Winners Are Built",
  "Code Like You Mean It",
  "Turn Pressure Into Power",
  "Interviewers Don’t Like You",
  "Skill Up Or Sit Out",
  "You’re Closer Than You Think",
  "Every Bug Makes You Better",
  "Push Past Average",
  "Your Next Breakthrough Starts Here",
  "Show Up. Lock In. Dominate.",
  "Make Them Remember Your Name",
  "Earn That Offer",
  "Your Hard Work Pays Dividends",
  "Prove Your Potential",
  "You’re Built For This",
  "Turn Doubt Into Drive",
  "One More Problem. One More Level.",
  "The Grind Makes You Great",
  "Nothing Beats Consistency",
  "Get Sharp. Stay Sharp.",
  "No Fear. Just Focus.",
  "Your Dream Role Is Waiting",
  "You Decide What Happens Next",
  "Don’t Hope. Prepare.",
  "Effort Is Your Edge",
  "This Is What Growth Feels Like",
  "Champions Train Daily",
  "Think Better. Code Better.",
  "Small Steps. Massive Results.",
  "Build Skills They Can’t Ignore",
  "This Is Your Proving Ground",
  "Step Up To The Challenge",
  "Turn Ambition Into Action",
  "You’re Coding Your Future",
  "Winners Aren’t Born, They Practice",
  "Your Competitors Are Practicing",
  "Stay Hungry, Stay Building",
  "Dreams Don’t Work Unless You Do",
  "The Only Way Is Through",
  "You’re More Capable Than You Think",
  "Today’s Grind, Tomorrow’s Offer",
  "Success Starts With One Problem",
  "Your Future Self Thanks You",
  "Make The Hard Stuff Look Easy",
  "Be Better Than Yesterday",
  "Pressure Creates Pros",
  "Discipline Beats Motivation",
  "You’re Here For A Reason",
  "This Is How You Level Up",
  "Fuck LeetCode",
  "Fuck NeetCode",
  "Fuck getcracked.io",
  "Pressure Makes Diamonds",
  "Assume Rumours To Be False",
  "Why Do You Doubt Yourself?",
  "What's Your Worst Nightmare?",
  "What's Your Best Day Ever?",
  "What's Your Best Night Ever?",
  "What's Your Best Week Ever?",
  "What's Your Best Month Ever?",
  "Make This Your New Life",
  "You Are The Best",
  "Are You Ready For This?",
  "You Don't Need Friends",
];

export default HERO_QUOTES;
